/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import type { Property, Tile, Token } from '../types';

/**
 * Standard Monopoly house cost by color group. Used at runtime via upgradeCost.
 */
const UPGRADE_COSTS: Record<string, number> = {
  PURPLE: 50,
  LIGHT_BLUE: 50,
  PINK: 100,
  ORANGE: 100,
  RED: 150,
  YELLOW: 150,
  GREEN: 200,
  DARK_BLUE: 200,
};

export const PROPERTIES: Property[] = [
  // PURPLE
  {
    id: 0,
    name: 'Ben Hill',
    price: 60,
    rent: [2, 10, 30, 90, 160, 250],
    upgradeCost: UPGRADE_COSTS.PURPLE,
    group: 'PURPLE',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 1,
    name: 'Adamsville',
    price: 60,
    rent: [4, 20, 60, 180, 320, 450],
    upgradeCost: UPGRADE_COSTS.PURPLE,
    group: 'PURPLE',
    owner: null,
    level: 0,
    mortgaged: false,
    image: '/adamsville.png',
  },

  // LIGHT BLUE
  {
    id: 2,
    name: 'Campton Road',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    upgradeCost: UPGRADE_COSTS.LIGHT_BLUE,
    group: 'LIGHT_BLUE',
    owner: null,
    level: 0,
    mortgaged: false,
    image: '/campton_road.png',
  },
  {
    id: 3,
    name: 'Camp Creek',
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    upgradeCost: UPGRADE_COSTS.LIGHT_BLUE,
    group: 'LIGHT_BLUE',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 4,
    name: 'SWATS',
    price: 120,
    rent: [8, 40, 100, 300, 450, 600],
    upgradeCost: UPGRADE_COSTS.LIGHT_BLUE,
    group: 'LIGHT_BLUE',
    owner: null,
    level: 0,
    mortgaged: false,
  },

  // PINK
  {
    id: 5,
    name: 'Edgewood',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    upgradeCost: UPGRADE_COSTS.PINK,
    group: 'PINK',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 6,
    name: 'Cabbagetown',
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    upgradeCost: UPGRADE_COSTS.PINK,
    group: 'PINK',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 7,
    name: 'Old 4th Ward',
    price: 160,
    rent: [12, 60, 180, 500, 700, 900],
    upgradeCost: UPGRADE_COSTS.PINK,
    group: 'PINK',
    owner: null,
    level: 0,
    mortgaged: false,
  },

  // ORANGE
  {
    id: 8,
    name: 'Mechanicsville',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    upgradeCost: UPGRADE_COSTS.ORANGE,
    group: 'ORANGE',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 9,
    name: 'Pittsburgh',
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    upgradeCost: UPGRADE_COSTS.ORANGE,
    group: 'ORANGE',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 10,
    name: 'Peoplestown',
    price: 200,
    rent: [16, 80, 220, 600, 800, 1000],
    upgradeCost: UPGRADE_COSTS.ORANGE,
    group: 'ORANGE',
    owner: null,
    level: 0,
    mortgaged: false,
  },

  // RED
  {
    id: 11,
    name: 'Bankhead',
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    upgradeCost: UPGRADE_COSTS.RED,
    group: 'RED',
    owner: null,
    level: 0,
    mortgaged: false,
    image: '/bankhead.png',
  },
  {
    id: 12,
    name: 'Bowen Homes',
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    upgradeCost: UPGRADE_COSTS.RED,
    group: 'RED',
    owner: null,
    level: 0,
    mortgaged: false,
    image: '/bowen_homes.png',
  },
  {
    id: 13,
    name: 'Simpson Road',
    price: 240,
    rent: [20, 100, 300, 750, 925, 1100],
    upgradeCost: UPGRADE_COSTS.RED,
    group: 'RED',
    owner: null,
    level: 0,
    mortgaged: false,
  },

  // YELLOW
  {
    id: 14,
    name: 'College Park',
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    upgradeCost: UPGRADE_COSTS.YELLOW,
    group: 'YELLOW',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 15,
    name: 'Riverdale',
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    upgradeCost: UPGRADE_COSTS.YELLOW,
    group: 'YELLOW',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 16,
    name: 'Forest Park',
    price: 280,
    rent: [24, 120, 360, 850, 1025, 1200],
    upgradeCost: UPGRADE_COSTS.YELLOW,
    group: 'YELLOW',
    owner: null,
    level: 0,
    mortgaged: false,
    image: '/Forest%20Park.jpg',
    description:
      'Known for the State Farmers Market and its rich railroad history. A hidden gem with easy access to everything south of the perimeter.',
  },

  // GREEN
  {
    id: 17,
    name: 'EAV',
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    upgradeCost: UPGRADE_COSTS.GREEN,
    group: 'GREEN',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 18,
    name: 'Gresham Road',
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    upgradeCost: UPGRADE_COSTS.GREEN,
    group: 'GREEN',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 19,
    name: 'Glenwood',
    price: 320,
    rent: [28, 150, 450, 1000, 1200, 1400],
    upgradeCost: UPGRADE_COSTS.GREEN,
    group: 'GREEN',
    owner: null,
    level: 0,
    mortgaged: false,
  },

  // DARK BLUE
  {
    id: 20,
    name: 'Zone 6',
    price: 350,
    rent: [35, 175, 500, 1100, 1300, 1500],
    upgradeCost: UPGRADE_COSTS.DARK_BLUE,
    group: 'DARK_BLUE',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 21,
    name: 'Kirkwood',
    price: 400,
    rent: [50, 200, 600, 1400, 1700, 2000],
    upgradeCost: UPGRADE_COSTS.DARK_BLUE,
    group: 'DARK_BLUE',
    owner: null,
    level: 0,
    mortgaged: false,
  },

  // RAILROADS — rent[0..3] = 1/2/3/4 owned
  {
    id: 22,
    name: 'Five Points',
    price: 200,
    rent: [25, 50, 100, 200, 0, 0],
    upgradeCost: 0,
    group: 'RAILROAD',
    owner: null,
    level: 0,
    mortgaged: false,
    image: '/five_points.png',
  },
  {
    id: 23,
    name: 'Airport',
    price: 200,
    rent: [25, 50, 100, 200, 0, 0],
    upgradeCost: 0,
    group: 'RAILROAD',
    owner: null,
    level: 0,
    mortgaged: false,
    image: '/airport.png',
  },
  {
    id: 24,
    name: 'West End',
    price: 200,
    rent: [25, 50, 100, 200, 0, 0],
    upgradeCost: 0,
    group: 'RAILROAD',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 25,
    name: 'Lenox Station',
    price: 200,
    rent: [25, 50, 100, 200, 0, 0],
    upgradeCost: 0,
    group: 'RAILROAD',
    owner: null,
    level: 0,
    mortgaged: false,
  },

  // UTILITIES — rent computed from dice total at runtime
  {
    id: 26,
    name: 'GA Power',
    price: 150,
    rent: [0, 0, 0, 0, 0, 0],
    upgradeCost: 0,
    group: 'UTILITY',
    owner: null,
    level: 0,
    mortgaged: false,
  },
  {
    id: 27,
    name: 'Clayton Water',
    price: 150,
    rent: [0, 0, 0, 0, 0, 0],
    upgradeCost: 0,
    group: 'UTILITY',
    owner: null,
    level: 0,
    mortgaged: false,
  },
];

export const BOARD_TILES: Tile[] = [
  { id: 0, type: 'GO', name: 'GO' },
  { id: 1, type: 'PROPERTY', name: 'Ben Hill', propertyId: 0 },
  { id: 2, type: 'COMMUNITY', name: 'Community Chest' },
  { id: 3, type: 'PROPERTY', name: 'Adamsville', propertyId: 1 },
  { id: 4, type: 'TAX', name: 'Income Tax', taxAmount: 200 },
  { id: 5, type: 'PROPERTY', name: 'Five Points', propertyId: 22 },
  { id: 6, type: 'PROPERTY', name: 'Campton Rd', propertyId: 2 },
  { id: 7, type: 'CHANCE', name: 'Chance' },
  { id: 8, type: 'PROPERTY', name: 'Camp Creek', propertyId: 3 },
  { id: 9, type: 'PROPERTY', name: 'SWATS', propertyId: 4 },
  { id: 10, type: 'JAIL', name: 'Fulton County Jail' },
  { id: 11, type: 'PROPERTY', name: 'Edgewood', propertyId: 5 },
  { id: 12, type: 'PROPERTY', name: 'Clayton Water', propertyId: 27 },
  { id: 13, type: 'PROPERTY', name: 'Cabbagetown', propertyId: 6 },
  { id: 14, type: 'PROPERTY', name: 'Old 4th Ward', propertyId: 7 },
  { id: 15, type: 'PROPERTY', name: 'Airport', propertyId: 23 },
  { id: 16, type: 'PROPERTY', name: 'Mechanicsville', propertyId: 8 },
  { id: 17, type: 'COMMUNITY', name: 'Community Chest' },
  { id: 18, type: 'PROPERTY', name: 'Pittsburgh', propertyId: 9 },
  { id: 19, type: 'PROPERTY', name: 'Peoplestown', propertyId: 10 },
  { id: 20, type: 'FREE_PARKING', name: 'Magic City Parking' },
  { id: 21, type: 'PROPERTY', name: 'Bankhead', propertyId: 11 },
  { id: 22, type: 'CHANCE', name: 'Chance' },
  { id: 23, type: 'PROPERTY', name: 'Bowen Homes', propertyId: 12 },
  { id: 24, type: 'PROPERTY', name: 'Simpson Rd', propertyId: 13 },
  { id: 25, type: 'PROPERTY', name: 'West End', propertyId: 24 },
  { id: 26, type: 'PROPERTY', name: 'College Park', propertyId: 14 },
  { id: 27, type: 'PROPERTY', name: 'Riverdale', propertyId: 15 },
  { id: 28, type: 'PROPERTY', name: 'GA Power', propertyId: 26 },
  { id: 29, type: 'PROPERTY', name: 'Forest Park', propertyId: 16 },
  { id: 30, type: 'GO_TO_JAIL', name: 'Go To Jail' },
  { id: 31, type: 'PROPERTY', name: 'EAV', propertyId: 17 },
  { id: 32, type: 'PROPERTY', name: 'Gresham Rd', propertyId: 18 },
  { id: 33, type: 'COMMUNITY', name: 'Community Chest' },
  { id: 34, type: 'PROPERTY', name: 'Glenwood', propertyId: 19 },
  { id: 35, type: 'PROPERTY', name: 'Lenox Station', propertyId: 25 },
  { id: 36, type: 'CHANCE', name: 'Chance' },
  { id: 37, type: 'PROPERTY', name: 'Zone 6', propertyId: 20 },
  { id: 38, type: 'TAX', name: 'Luxury Tax', taxAmount: 75 },
  { id: 39, type: 'PROPERTY', name: 'Kirkwood', propertyId: 21 },
];

export const TOKENS: Token[] = [
  { name: 'Box Chevy', description: 'Heavy metal. Slow but respectful.' },
  { name: 'Hashbrowns', description: 'Scattered, smothered, covered.' },
  { name: 'Trap Phone', description: 'Screen cracked. Money stacked.' },
  { name: 'Double Cup', description: 'Lean with it. Rock with it.' },
  { name: 'Wing Basket', description: '10 piece lemon pepper wet.' },
  { name: 'Shopping Bag', description: 'Lenox Mall parking lot warrior.' },
  { name: 'EBT Card', description: 'Accepted everywhere... mostly.' },
];

export const PLAYER_COLORS = [
  'bg-blue-500',
  'bg-red-500',
  'bg-green-500',
  'bg-yellow-500',
  'bg-purple-500',
  'bg-pink-500',
];

export const STARTING_MONEY = 1500;
export const GO_BONUS = 200;
export const JAIL_BAIL = 50;
export const JAIL_POSITION = 10;
